In [1]:
from CandidateNetwork import CandidateNetwork
from Candidate import Candidate
import numpy as np
import tensorflow as tf
from typing import List
import random

In [ ]:
x = tf.ones(shape=(8,16,4))
x1 = tf.transpose(x, [0, 2, 1])
l = tf.keras.layers.Dense(10)

ee = l(x1)
e = tf.reduce_sum(ee, axis=1, keepdims=False)
e

In [35]:
depth=6
dim=3
n=10
actions=np.array([random.randrange(0, depth) for i in range(dim * n)])
aa = np.reshape(actions, newshape=(n,dim))
print(aa)
d3 = tf.one_hot(aa, depth=depth)
tf.reshape(d3, shape=(n, dim * depth))


[[0 3 4]
 [2 5 0]
 [2 3 4]
 [0 1 0]
 [0 2 2]
 [1 3 1]
 [5 5 4]
 [1 3 5]
 [1 3 5]
 [3 0 2]]


<tf.Tensor: shape=(10, 18), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.]], dtype=float32)>

In [48]:
a= np.array([i for i in range(10 )])
b= np.array([i for i in range(10 )])
print(np.stack([a,b]))

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [5]:
from Ideology import Ideology
from Party import Republicans
from CandidateModel import CandidateModel
c = Candidate("foo", Republicans, Ideology(np.array([1,2,3])), 0)
cm = CandidateModel(10, 3, 10, 32, .001)


array([1, 2, 3])